spring:
  application:
    name: member
  redis:
      database: 0
      host : 127.0.0.1
      port : 6379
      password: 123456
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: 1
      timeout: 5000
  datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test2?useUnicode=true&characterEncoding=utf-8
        username: root
        password: 123456
eureka:
  instance:
    # 每间隔1s，向服务端发送一次心跳，证明自己依然”存活“
    lease-renewal-interval-in-seconds: 1
    # 告诉服务端，如果我2s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-expiration-duration-in-seconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8083

mybatis:
  mapper-locations: classpath:mapper/*.xml