spring:
  application:
    name: zuul
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
server:
  port: 8084

zuul:
  routes:
    api-a:
      path: /order/**
      service-id: order
    api-b:
      path: /member/**
      service-id: member
    api-c:
      path: /authority/**
      service-id: authority


#开启断路器
feign:
   hystrix:
     enabled: true
###超时时间
hystrix:
   command:
     default:
       execution:
        isolation:
         thread:
          timeoutInMilliseconds: 4000

