spring:
  data:
    mongodb:
#      uri: mongodb://localhost:27017/springboot-db
      username: root
      password: ybya2018
      host: 192.168.0.108
      port: 27017
      database: springboot-test